---
driver:
  name: dokken
  privileged: true
  env: [CHEF_LICENSE=accept]

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  -
    name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        # - RUN /usr/bin/apt-get upgrade -y
  -
    name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        # - RUN /usr/bin/apt-get upgrade -y
  -
    name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install sudo
  -
    name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo
  -
    name: amazonlinux
    driver:
      image: dokken/amazonlinux
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo
  -
    name: amazonlinux-2
    driver:
      image: dokken/amazonlinux-2
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo
  -
    name: fedora-latest
    driver:
      image: dokken/fedora-latest
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN dnf -y install sudo
  -
    name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        # - RUN /usr/bin/apt-get upgrade -y
  -
    name: ubuntu-18.04
    driver:
      image: taqtiqa/dokken-images:ubuntu-18.04-latest
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        # - RUN /usr/bin/apt-get upgrade -y
  -
    name: opensuse-leap
    driver:
      image: dokken/opensuse-leap
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN zypper --non-interactive install sudo

suites:
  - name: resources
    provisioner:
      policyfile: test/fixtures/cookbooks/resources/Policyfile.rb
    verifier:
      inspec_tests:
        - test/integration/resources
  - name: recipes
    provisioner:
      policyfile: test/fixtures/cookbooks/recipes/Policyfile.rb
    verifier:
      inspec_tests:
        - test/integration/recipes
  - name: issues
    provisioner:
      policyfile: test/fixtures/cookbooks/issues/Policyfile.rb
    verifier:
      inspec_tests:
        - test/integration/issues
  # - name: system_install
  #   provisioner:
  #     policyfile: test/fixtures/cookbooks/resources/system_install.pf.rb
  #   verifier:
  #     inspec_tests:
  #       - test/integration/resources/system_install
  # - name: global
  #   provisioner:
  #     policyfile: test/fixtures/cookbooks/resources/global.pf.rb
  #   verifier:
  #     inspec_tests:
  #       - test/integration/resources/global
  #   attributes:
