---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true
  policyfile: Policyfile.rb

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: fedora-latest
  - name: debian-8
  - name: debian-9
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: opensuse-leap

suites:
  - name: pkg
    run_list: recipe[test::pkg]
    includes: [centos-7]
  - name: global
    run_list: recipe[test::global]
  - name: julia_uninstall
    run_list: recipe[test::julia_uninstall]
    includes: [ubuntu-18.04]
  - name: system_install
    run_list: recipe[test::system_install]
    includes: [centos-7]
  - name: user_install
    run_list: recipe[test::user_install]
    includes: [centos-7]
  - name: custom_group_install
    run_list: recipe[test::custom_group_install]
    includes: [centos-7]
