name 'jlenv'
maintainer 'Mark Van de Vyver'
maintainer_email 'mark@taqtiqa.com'
issues_url 'https://github.com/jlenv/jlenv-cookbook/issues'
source_url 'https://github.com/jlenv/jlenv-cookbook'
license 'Apache-2.0'
description 'Manages jlenv and plugins for Julia installations.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.3.0'
chef_version '>= 14.0'

supports 'ubuntu'
supports 'linuxmint'
supports 'debian'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'opensuse'
supports 'mac_os_x'
